version: "3.7"

services:

  server:
    container_name: rmi-server
    build:
      context: .
      dockerfile: ./server-code/Dockerfile
      args:
        JAVA_VERSION: "8-slim"
    volumes:
      - ./shared:/shared
    networks:
      - default
    ports:
      - 1099:1099

  client:
    container_name: rmi-client
    build:
      context: .
      dockerfile: ./client-code/Dockerfile
      args:
        JAVA_VERSION: "8-slim"
    depends_on:
      - server
    volumes:
      - ./shared:/shared
    networks:
      - default
    environment:
      - REGISTRY_HOST=rmi-server
    stdin_open: true
    tty: true

networks:
  default:
    driver: bridge